### PR TITLE
PR for the first change to this branch

### PR DESCRIPTION
**Pull request by andrewrho1**
PR: this was the description for my first commit, can I get this to CU?

### CODE REVIEW

**Comment by andrewrho1** [comment]
Task linked: [CU-862jfz2yf Product per page function](https://app.clickup.com/t/862jfz2yf)

**Comment by andrewrho1** [comment]
Task linked: [CU-862jfz2yf Product per page function](https://app.clickup.com/t/862jfz2yf)

**Review by andrewrho1 — COMMENTED** [review]
need to add a period at the end of the sentence.

**Review by loupinski — CHANGES_REQUESTED** [review]
I agree we need to add a period at the end.

**Review by loupinski — APPROVED** [review]
Now looks good

**Pull request merged**
