### PR TITLE
CU-862jfz2yf v3 change to the readme file

### PR DESCRIPTION
**Pull request by andrewrho1**
extended description for v3

### CODE REVIEW

**Comment by andrewrho1** [comment]
Task linked: [CU-862jfz2yf Product per page function](https://app.clickup.com/t/862jfz2yf)

**Review by loupinski — COMMENTED** [review]
Here's a comment without task id

**Review by loupinski — CHANGES_REQUESTED** [review]
here's a requested change, let's add a few more words

**Review by loupinski — APPROVED** [review]
looks good!

**Review by loupinski — COMMENTED** [review]
CU-862jfz2yf comment

**Pull request merged**
